services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend/data.db:/app/data.db
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      # make CRA listen on 0.0.0.0 instead of localhost
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
